import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Confer Solutions privacy policy and data protection practices.",
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-900 dark:to-slate-800">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-4">Privacy Policy</h1>
            <p className="text-xl text-slate-600 dark:text-slate-300">
              This Privacy Policy explains how Confer Inc. collects, uses, and safeguards your information when you use our website and mobile application.
            </p>
            <div className="mt-4 text-sm text-slate-500 dark:text-slate-400">Last updated: January 17, 2025</div>
          </div>

          {/* Content */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 md:p-12">
            <div className="prose prose-slate dark:prose-invert max-w-none">
              {/* 1. Introduction */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. Introduction</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Welcome to Confer Inc.<br />
                  Confer Inc. (“us”, “we”, or “our”) operates <a href="https://confersolutions.ai" className="text-blue-600 dark:text-blue-400 hover:underline">https://confersolutions.ai</a> and the Confer mobile application.<br />
                  Our Privacy Policy governs your use of our software, APIs, applications, mobile applications, mobile website otherwise linked or connected thereto (“Platform”) and Confer mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Platform.
                </p>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We use your data to provide and improve Platform. By using Platform, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br />
                  Our Terms of Service (“Terms”) govern all use of our Platform and together with the Privacy Policy constitutes your agreement with us (“agreement”).
                </p>
              </section>

              {/* 2. Definitions */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. Definitions</h2>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 space-y-2">
                  <li><strong>SERVICE/PLATFORM</strong> means the <a href="https://confersolutions.ai" className="text-blue-600 dark:text-blue-400 hover:underline">https://confersolutions.ai</a> website and Confer mobile application operated by Confer Inc.</li>
                  <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                  <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Platform or from Service infrastructure itself (for example, the duration of a page visit).</li>
                  <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
                  <li><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
                  <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> mean any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
                  <li><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</li>
                  <li><strong>THE USER</strong> is the individual using our Platform. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
                </ul>
              </section>

              {/* 3. Information Collection and Use */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. Information Collection and Use</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We collect several different types of information for various purposes to provide and improve our Platform to you.
                </p>
              </section>

              {/* 4. Types of Data Collected */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Types of Data Collected</h2>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Personal Data</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  While using our Platform, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                </p>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Usage Data</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We may also collect information that your browser sends whenever you visit our Platform or when you access Service by or through a mobile device (“Usage Data”).
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>IP address, browser type, browser version</li>
                  <li>Pages of our Platform that you visit, time and date of your visit, time spent on those pages</li>
                  <li>Unique device identifiers and other diagnostic data</li>
                  <li>Mobile device type, unique ID, IP address, operating system, browser type</li>
                </ul>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Location Data</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Platform, to improve and customize our Platform. You can enable or disable location services when you use our Platform at any time by way of your device settings.
                </p>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Tracking Cookies Data</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We use cookies and similar tracking technologies to track the activity on our Platform and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Platform. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Platform.
                </p>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Other Data</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  While using our Platform, we may also collect the following information: (1) telephone number (work, mobile) and, (2) office location.
                </p>
              </section>

              {/* 5. Use of Data */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">5. Use of Data</h2>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 space-y-2">
                  <li>to provide and maintain our Platform;</li>
                  <li>to notify you about changes to our Platform;</li>
                  <li>to allow you to participate in interactive features of our Platform when you choose to do so;</li>
                  <li>to provide customer support;</li>
                  <li>to gather analysis or valuable information so that we can improve our Platform;</li>
                  <li>to monitor the usage of our Platform;</li>
                  <li>to detect, prevent and address technical issues;</li>
                  <li>to fulfil any other purpose for which you provide it;</li>
                  <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                  <li>to carry out market research, compliance reporting, cross-selling products to other users;</li>
                  <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
                  <li>to provide you with news, special offers and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                  <li>in any other way we may describe when you provide the information;</li>
                  <li>for any other purpose with your consent.</li>
                </ul>
              </section>

              {/* 6. Retention Of Data */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">6. Retention Of Data</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Platform, or we are legally obligated to retain this data for longer time periods.
                </p>
              </section>

              {/* 7. Transfer of Data */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">7. Transfer of Data</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                </p>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
                </p>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Confer Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>
              </section>

              {/* 8. Disclosure of Data */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">8. Disclosure of Data</h2>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Disclosure for Law Enforcement</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                </p>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Business Transaction</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
                </p>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Other Cases</h3>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>to our subsidiaries and affiliates;</li>
                  <li>to contractors, service providers, and other third parties we use to support our business;</li>
                  <li>to fulfill the purpose for which you provide it;</li>
                  <li>for the purpose of including your company’s logo on our website;</li>
                  <li>for any other purpose disclosed by us when you provide the information;</li>
                  <li>with your consent in any other cases;</li>
                  <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
                </ul>
              </section>

              {/* 9. Security of Data */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">9. Security of Data</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>
              </section>

              {/* 10. Your Data Protection Rights Under GDPR */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" className="text-blue-600 dark:text-blue-400 hover:underline">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a>
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>the right to access, update or to delete the information we have on you;</li>
                  <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
                  <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
                  <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
                  <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable, and commonly used format;</li>
                  <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
                </ul>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Platform without some necessary data.<br />
                  You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                </p>
              </section>

              {/* 11. Your Data Protection Rights Under CalOPPA */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">11. Your Data Protection Rights Under the California Privacy Protection Act (CalOPPA)</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: <a href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" className="text-blue-600 dark:text-blue-400 hover:underline">CalOPPA</a>
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>users can visit our site anonymously;</li>
                  <li>our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;</li>
                  <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
                  <li>users are able to change their personal information by emailing us at <a href="mailto:info@confersolutions.ai" className="text-blue-600 dark:text-blue-400 hover:underline">info@confersolutions.ai</a>.</li>
                </ul>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">Our Policy on “Do Not Track” Signals:</h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
                </p>
              </section>

              {/* 12. Your Data Protection Rights Under CCPA */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">12. Your Data Protection Rights Under the California Consumer Privacy Act (CCPA)</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li>What personal information we have about you. If you make this request, we will return to you:
                    <ul className="list-disc list-inside ml-6">
                      <li>The categories of personal information we have collected about you.</li>
                      <li>The categories of sources from which we collect your personal information.</li>
                      <li>The business or commercial purpose for collecting or selling your personal information.</li>
                      <li>The categories of third parties with whom we share personal information.</li>
                      <li>The specific pieces of personal information we have collected about you.</li>
                      <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
                      <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
                    </ul>
                  </li>
                  <li>To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</li>
                  <li>To stop selling your personal information. If you submit a request to stop selling your personal information, we will stop selling it. If you are a California resident, to opt-out of the sale of your personal information, click “Do Not Sell My Personal Information” at the bottom of our home page to submit your request.</li>
                </ul>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.<br />
                  To exercise your California data protection rights described above, please send your request(s) by one of the following means:<br />
                  By email: <a href="mailto:info@confersolutions.ai" className="text-blue-600 dark:text-blue-400 hover:underline">info@confersolutions.ai</a>
                </p>
              </section>

              {/* 13. Service Providers */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">13. Service Providers</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Platform is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
              </section>

              {/* 14. Analytics */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">14. Analytics</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We may use third-party Service Providers to monitor and analyze the use of our Platform.
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li><strong>Google Analytics:</strong> <a href="https://policies.google.com/privacy?hl=en" className="text-blue-600 dark:text-blue-400 hover:underline">Google Privacy Policy</a></li>
                  <li><strong>Cloudflare analytics:</strong> <a href="https://www.cloudflare.com/privacypolicy/" className="text-blue-600 dark:text-blue-400 hover:underline">Cloudflare Privacy Policy</a></li>
                  <li><strong>Segment.io:</strong> <a href="https://segment.com/legal/privacy/" className="text-blue-600 dark:text-blue-400 hover:underline">Segment.io Privacy Policy</a></li>
                </ul>
              </section>

              {/* 15. CI/CD Tools */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">15. CI/CD Tools</h2>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li><strong>GitHub:</strong> <a href="https://help.github.com/en/articles/github-privacy-statement" className="text-blue-600 dark:text-blue-400 hover:underline">GitHub Privacy Policy</a></li>
                  <li><strong>GitLab CI/CD:</strong> <a href="https://about.gitlab.com/privacy/" className="text-blue-600 dark:text-blue-400 hover:underline">GitLab Privacy Policy</a></li>
                </ul>
              </section>

              {/* 16. Advertising */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">16. Advertising</h2>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li><strong>Google AdSense DoubleClick Cookie:</strong> <a href="http://www.google.com/ads/preferences/" className="text-blue-600 dark:text-blue-400 hover:underline">Google Ads Settings</a></li>
                  <li><strong>Bing Ads:</strong> <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" className="text-blue-600 dark:text-blue-400 hover:underline">Microsoft Privacy Statement</a></li>
                  <li><strong>AdMob by Google:</strong> <a href="https://support.google.com/ads/answer/2662922?hl=en" className="text-blue-600 dark:text-blue-400 hover:underline">AdMob Opt-out</a></li>
                </ul>
              </section>

              {/* 17. Behavioral Remarketing */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">17. Behavioral Remarketing</h2>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li><strong>Google Ads (AdWords):</strong> <a href="http://www.google.com/settings/ads" className="text-blue-600 dark:text-blue-400 hover:underline">Google Ads Settings</a></li>
                  <li><strong>Bing Ads Remarketing:</strong> <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" className="text-blue-600 dark:text-blue-400 hover:underline">Microsoft Privacy Statement</a></li>
                  <li><strong>Twitter:</strong> <a href="https://twitter.com/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">Twitter Privacy Policy</a></li>
                  <li><strong>Facebook:</strong> <a href="https://www.facebook.com/privacy/explanation" className="text-blue-600 dark:text-blue-400 hover:underline">Facebook Data Policy</a></li>
                  <li><strong>Pinterest:</strong> <a href="https://about.pinterest.com/en/privacy-policy" className="text-blue-600 dark:text-blue-400 hover:underline">Pinterest Privacy Policy</a></li>
                </ul>
              </section>

              {/* 18. Payments */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">18. Payments</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  We may provide paid products and/or services within Platform. In that case, we use third-party services for payment processing (e.g., payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                </p>
                <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 mb-6 space-y-2">
                  <li><strong>PayPal or Braintree:</strong> <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" className="text-blue-600 dark:text-blue-400 hover:underline">PayPal Privacy Policy</a></li>
                  <li><strong>Apple Store In-App Payments:</strong> <a href="https://www.apple.com/legal/privacy/en-ww/" className="text-blue-600 dark:text-blue-400 hover:underline">Apple Privacy Policy</a></li>
                  <li><strong>Google Play In-App Payments:</strong> <a href="https://policies.google.com/privacy?hl=en&gl=us/" className="text-blue-600 dark:text-blue-400 hover:underline">Google Privacy Policy</a></li>
                  <li><strong>Stripe:</strong> <a href="https://stripe.com/us/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">Stripe Privacy Policy</a></li>
                  <li><strong>Plaid:</strong> <a href="https://plaid.com/legal/" className="text-blue-600 dark:text-blue-400 hover:underline">Plaid Privacy Policy</a></li>
                  <li><strong>Square:</strong> <a href="https://squareup.com/us/en/legal/general/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">Square Privacy Policy</a></li>
                </ul>
              </section>

              {/* 19. Links to Other Sites */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">19. Links to Other Sites</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Our Platform may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </section>

              {/* 20. Children’s Privacy */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">20. Children’s Privacy</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  Our Services are not intended for use by minors. We do not knowingly collect personally identifiable information from minors. If you become aware that a minor has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from minors without verification of parental consent, we take steps to remove that information from our servers.
                </p>
              </section>

              {/* 21. Changes To This Privacy Policy */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">21. Changes To This Privacy Policy</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Platform, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </section>

              {/* 22. Contact Us */}
              <section>
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">22. Contact Us</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                  If you have any questions about this Privacy Policy, please contact us:<br />
                  By email: <a href="mailto:info@confersolutions.ai" className="text-blue-600 dark:text-blue-400 hover:underline">info@confersolutions.ai</a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
