import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "End User License Agreement (EULA)",
  description: "Confer Solutions End User License Agreement.",
}

export default function EulaPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-900 dark:to-slate-800">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-4">End User License Agreement (EULA)</h1>
            <p className="text-xl text-slate-600 dark:text-slate-300">
              Please review our End User License Agreement. This page outlines your rights and responsibilities as a user of Confer Solutions.
            </p>
            <div className="mt-4 text-sm text-slate-500 dark:text-slate-400">Last updated: January 17, 2025</div>
          </div>

          {/* Content */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 md:p-12">
            <div className="prose prose-slate dark:prose-invert max-w-none">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">End User License Agreement</h2>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">1. Introduction</h3>
                <p>This Agreement is between Confer Inc., a company based in 580 California St. San Francisco, CA 94104 (“we”, “us”, “our”) and you, the user (“End User”, “you”, “your”, etc.). Please read this entire Agreement, which governs your use of the Platform as defined in our Terms of Service. This Agreement is hereby through this reference construed as a part of our Terms of Service. In the event of any conflict between the Terms of Service and this Agreement, the Terms of Service shall prevail.</p>
                <p>This Agreement may be periodically updated, and your continued use of the Platform after we notify you of such updates constitutes your acceptance of its terms. If you do not accept the updated terms as may be posted by us from time to time your access to the Platform shall be terminated immediately. By installing, copying, or otherwise using the Platform, you understand that you will adhere to the terms of this Agreement and Terms and all other operating rules, policies, and procedures that may be issued periodically on the Platform by us, each of which is incorporated by reference periodically by us.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">2. Defined Terms</h3>
                <ul>
                  <li><strong>2.1 “Account”</strong> means your user account created by you through the Platform.</li>
                  <li><strong>2.2 “Agreement”</strong> means this End User License Agreement</li>
                  <li><strong>2.3 “Intellectual Property Rights”</strong> means all (a) patents, patent disclosures, and inventions (whether patentable or not), (b) trademarks, service marks, trade dress, trade names, logos, graphic design, corporate names, and domain names, together with all of the goodwill associated therewith, (c) copyrights and copyrightable works, mask works, and rights in data and databases, (d) trade secrets, know-how, and other confidential information, and (e) all other intellectual property rights, in each case whether registered or unregistered and including all applications for, and renewals or extensions of, such rights, and all similar or equivalent rights or forms of protection in any part of the world.</li>
                  <li><strong>2.4 “Platform”</strong> means our blockchain based mortgage loan customizer application. “Platform” includes related services, the accompanying manual(s), and other written files, electronic or online materials or documentation, and any and all copies of such Platform and its materials.</li>
                  <li><strong>2.5 “Third Party Services”</strong> The Platform may display, include, or make available third-party content including data, information, applications and other products and services. The Platform may also include links to third-party websites.</li>
                  <li><strong>2.6 “Updates”</strong> means including without limits all contents of files in any media with which this Agreement is provided, all successor upgrades, revisions, patches, enhancements, fixes, modifications, copies, additions, or maintenance releases of the Platform, licensed to you by us. “User Generated Content” means including, without limits, all data generated by you through your inputs or via Platform usage.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">3. Binding Legal Agreement</h3>
                <p>This Agreement creates a binding legal agreement between you and us with respect to the Platform and Updates (unless an Update is given by a separate license in which case the terms of that license will govern) you install. By signing or providing your consent, and agreeing to the terms of this Agreement, you also agree to adhere to all our Terms available for your perusal at <a href="https://confersolutions.ai/terms" target="_blank" rel="noopener noreferrer">Terms of Service</a></p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">4. Service Limitation and Scope</h3>
                <p>The Platform is solely a software facilitating comparison between products offered by third parties. The Platform simply helps compare product offerings of lenders, third party providers, etc. to help you find the best offers by sifting through all the various product offerings. Confer Inc. nor any of its owners, operators, employees, contractors, or affiliates are an investment advisory service or a registered/ licensed investment advisor, broker, loan originator, loan underwriter, and do not claim to recommend or suggest which products users should buy. We shall not be liable for any purchase decisions made by you based upon any content we provide you.</p>
                <p>We are not qualified to give out financial advice, investment strategies, or any other advice. We specifically disclaim any and all liability or loss arising out of any action taken in reliance on the content we provide you, including but not limited to market value or other loss on the sale or purchase of any, property, product, service, security, instrument, or any other matter.</p>
                <p>We do not provide any risk based product pricing which essentially means that the any products displayed for you on the Platform are not provided according to your credit score. The third-party service providers who own the products displayed on the Platform reserve the right to deny you any products and such decisions for acceptance or denial to sell you any products shall not render Confer Inc. liable for including without limits, any claims, damages, etc. We hereby expressly disclaim all liabilities in this regard.</p>
                <p>We are not affiliated with or have any other relationship with any lenders, third-party providers as may be displayed on the Platform nor with any applicable regulatory bodies. We do not endorse the services of any lenders, third-party providers, and we hereby through this reference disclaim all liabilities arising out of the same under all circumstances. The scope of our service is limited to the services mentioned herein, and our Terms.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">5. Eligibility</h3>
                <p>To enter into this Agreement, you must be an adult of the legal age of majority in your country of residence. You should be legally and financially responsible for all actions using or accessing the Platform, including the actions of anyone you allow to access to your Account. You hereby affirm that you have reached the legal age of majority, understand, and accept this Agreement.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">6. License Grant</h3>
                <p>In consideration of payment of requisite fees as may be set out on the Platform or conveyed to you otherwise, and subject to any system requirements, the Platform is solely licensed to you, not sold, and you hereby acknowledge and agree that no title or ownership in the Platform is being transferred or assigned and, this Agreement should not be construed as a sale of any rights in the Platform. After the authorized release date, we grant to you a limited, non-exclusive, non-transferable license to use the Platform for personal use. Any rights that are not explicitly granted to you are reserved by us including the Intellectual Property Rights in the Platform. We retain the right to audit your use of the Platform and verify compliance with our terms and conditions. You hereby agree to cooperate with our audit and provide reasonable assistance and access to information.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">7. License Limitations</h3>
                <p>The license granted under this Agreement is subject to limitations. You hereby through this reference, specifically agree not to:</p>
                <ul>
                  <li>7.1 distribute, rent, lease, convert into convertible currency, sublicense, or otherwise transfer or assign the Platform, or make it available on a network to other users without our express prior written consent or as expressly set forth in this Agreement;</li>
                  <li>7.2 modify, adapt, translate, reverse engineer, decompile or disassemble the Platform;</li>
                  <li>7.3 create derivative works from the Platform;</li>
                  <li>7.4 remove or modify any proprietary notices, marks, or labels contained on or within the Platform;</li>
                  <li>7.5 copy, publicly perform or broadcast the Platform in an unauthorized manner;</li>
                  <li>7.6 disable any feature which limits the use of the Platform services;</li>
                  <li>7.7 use, exploit any part of the Platform to provide commercial services to third parties;</li>
                  <li>7.8 violate our Agreement for any online features of the Platform;</li>
                  <li>7.9 use the Platform in a manner which, in our sole discretion, interferes with the Platform’s ability to offer its services; or transport, export, or re-export (directly or indirectly) into any country forbidden to receive the Platform by any applicable export laws or regulations or economic sanctions or otherwise violate any laws or regulations, which may be amended from time to time.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">8. Ownership</h3>
                <p>All title, ownership rights, and Intellectual Property Rights in and to the Platform are owned by us, our affiliates, licensors, etc. The Platform is protected by the applicable copyright act, international copyright treaties, conventions, and other laws. The Platform may contain certain licensed materials, and our licensors may protect their rights in the event of any violation of this Agreement. NOTWITHSTANDING ANYTHING TO THE CONTRARY, YOU ACKNOWLEDGE AND AGREE THAT YOU SHALL HAVE NO OWNERSHIP OR OTHER PROPERTY INTEREST IN ANY ACCOUNT STORED OR HOSTED ON OUR SYSTEMS. WE MAY SUSPEND, TERMINATE, MODIFY OR DELETE ANY OF THESE ACCOUNTS AT ANY TIME FOR ANY REASON OR NO REASON, WITH OR WITHOUT NOTICE TO YOU IF YOU ARE FOUND IN VIOLATION OF OUR TERMS AND POLICIES.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">9. Third Party Services</h3>
                <p>The Platform may provide you to links to other services, or resources on the Internet including the Third-Party Services. Other websites, services or resources may contain links to the Platform. When you access Third Party Services on the Platform, you shall do so at your own risk. These Third-Party Services are not controlled by us, and you agree that we shall not be responsible or liable for including but not limited to the content, functions, accuracy, legality, appropriateness, or any other aspect of such Third-Party Services. The inclusion of any such link shall not imply our endorsement or any association in any way between us and their operators. You also agree that we will not be responsible or liable in any case, either directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such Third-Party Services.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">10. Privacy; Information Collection and Usage</h3>
                <p>By using the Platform, you agree to the collection, retention, processing, and use of your information under privacy policy made available to you on <a href="http://wordpress-zw8ogwcg4wkooks8o804kggo.144.126.158.171.sslip.io/privacy/" target="_blank" rel="noopener noreferrer">Privacy Policy</a> which can be used to uniquely identify you for the purpose of providing the services. By using the Platform, you consent to the information collection and usage terms set forth in this section and our Privacy Policy, including (where applicable) (i) the transfer of any personal information and other information to us, our affiliates, vendors, and business partners, and to certain other third parties, such as governmental authorities, in the United States; (ii) other uses and disclosures of your personal information or other information as specified in the above-referenced Privacy Policy, as amended from time to time. If you do not want your information used or shared in this manner, then you should not use the Platform. We intend to protect your information from being intercepted, accessed, used, or disclosed by unauthorized persons. Your information may also be accessible to the third parties during the usage of the Platform, but within limitations and we will not transfer or submit your personal information to third parties such as your username or password. We will not be responsible if your confidential information becomes accessible to the third parties that you transfer directly to the third parties during the usage of Platform. We will not be liable if your data, process, documents etc. are partly or fully distorted or lost and it is your own discretion to prevent access to your device for any misuse.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">11. Disclaimer</h3>
                <p>The use of the Platform is done at your own discretion and risk and with agreement that you will be solely responsible for any damage or financial loss that results from such activities. No advice or information, whether oral or written, obtained by you from the Platform or us shall create any warranty for the Platform. The material contained in the Platform or provided by the Platform is for informational purposes only. Nothing in the Platform constitutes or forms a part of any offer for sale or subscription of, or any invitation to offer to buy or subscribe for, any securities, nor should it or any part of it form the basis of or be relied upon in any connection with any contract or commitment whatsoever. The material is not to be construed as an offer or a recommendation to buy or sell a security. Past performance is no guarantee of future returns.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">12. Limitation of Liability</h3>
                <p>THE USE OF THE PLATFORM OFFERED BY US IS ENTIRELY AT YOUR OWN RISK. IN NO CASE SHALL WE, NOR OUR OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, PARTNERS, SUPPLIERS, CONTENT PROVIDERS, OR ANY USERS BE LIABLE TO YOU UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE, OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH REGARDS TO THE PLATFORM FOR: (I) ANY LOST PROFITS, LOSS IN REVENUE, LOSS OF GOODWILL, ANY DATA LOSS, LOSS OF USE, COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, OTHER INTANGIBLE LOSSES, OR INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, COMPENSATORY, EXEMPLARY, RELIANCE, PUNITIVE, LIQUIDATED, OR ANY SIMILAR CONSEQUENTIAL DAMAGES OF ANY TYPE WHATSOEVER (HOWEVER ARISING), (II) DEVICE FAILURE OR MALFUNCTION (III) ANY, VIRUSES, BUGS, TROJAN HORSES, OR THE LIKE (REGARDLESS OF THE SOURCE OF ORIGIN), (IV) ANY PERSONAL INJURY OR HARM, INCLUDING DEATH, WHICH IS CAUSED BY YOUR USE OR MISUSE OF THE PLATFORM, (V) ANY CLAIMS, DEMANDS, OR DAMAGES ARISING OUT OF OR RELATING TO ANY DISPUTE BETWEEN YOU AND ANY OTHER USER OF THE PLATFORM, OR (VI) ANY DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) OR GREATER THAN ANY AMOUNTS PAID BY YOU FOR USING OF THE PLATFORM DURING THE IMMEDIATELY PREVIOUS THREE (3) MONTH PERIOD. REMEDIES UNDER THIS AGREEMENT ARE EXCLUSIVE AND ARE LIMITED TO THOSE EXPRESSLY PROVIDED FOR IN THIS AGREEMENT. NOTHING IN THESE THIS AGREEMENT SHALL BE DEEMED TO EXCLUDE OR LIMIT YOUR LIABILITY IN RESPECT OF ANY INDEMNITY GIVEN BY YOU UNDER THIS AGREEMENT.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">13. Warranties and Representation</h3>
                <p>THE PLATFORM IS PROVIDED “AS IS”, “AS AVAILABLE” BASIS. THE USE OF PLATFORM AND IS AT THE USER’S SOLE RISK. THE PLATFORM IS PROVIDED WITHOUT WARRANTY, REPRESENTATION, OR GUARANTEE OF ANY KIND WHATSOEVER, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,  ANY WARRANTIES OF TITLE OR ACCURACY AND ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED, WITH THE SOLE EXCEPTION OF WARRANTIES (IF ANY) WHICH CANNOT BE EXPRESSLY EXCLUDED UNDER APPLICABLE LAW. WE, OUR DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, PARTNERS, AND CONTENT PROVIDERS DO NOT WARRANT THAT: (I) THE PLATFORM ARE OR WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME, INSTANCE OR LOCATION; (II) ANY DEFECTS MATERIAL OR NOT, OR ERRORS WILL BE CORRECTED; (III) ANY/ALL CONTENT OR PLATFORM AVAILABLE AT OR THROUGH THE PLATFORM IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; (IV) ANY/ALL INFORMATION IS COMPLETE, ACCURATE, UP-TO-DATE, OR RELIABLE; (V) ANY PARTICULAR SERVICE, CONTENT, OR PRODUCT REFERRED TO IN THE PLATFORM IS SAFE, APPROPRIATE, OR EFFECTIVE FOR YOUR AND/OR YOUR EMPLOYEES; (VI) THAT RESULTS OF USING THE PLATFORM PROVIDED BY US WILL MEET YOUR REQUIREMENTS(VII) THE USE OF THE PLATFORM PROVIDED BY US SHALL COMPLY WITH ANY LAWS, RULES, REGULATIONS, REQUIREMENTS, POLICIES, QUALIFICATIONS, OR BEST PRACTICES, INCLUDING BUT NOT LIMITED TO PRIVACY LAWS, PROFESSIONAL LICENSURE, OR REIMBURSEMENT; (VIII) THE USE OF THE PLATFORM SHALL NOT RESULT IN LEGAL DUTIES OR LIABILITY. WE DO NOT GUARANTEE IN ANY INSTANCE THAT ANY PARTICULAR CONTENT OR MATERIAL SHALL BE MADE AVAILABLE THROUGH THE PLATFORM.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">14. Export Controls</h3>
                <p>The use of this Platform is subject to the U.S. Export Administration Regulations. You agree to the following: (a) you are not a citizen, national or resident of, and am not under the control of, the government of Cuba, Iran, North Korea, Syria, Sudan nor any other country to which the United States has prohibited export; (b) you will not export or re-export the Platform, directly or indirectly, neither to the above mentioned countries nor to citizens, nationals or residents of those countries; (c) you are not listed on the United States Department of Treasury lists of Specially Designated Nationals, Specially Designated Terrorists, and Specially Designated Narcotic Traffickers, nor are you listed on the United States Department of Commerce Table of Denial Orders; (d) you will not export or re-export the Platform, directly, or indirectly, to persons on the above mentioned lists; and (e) you will not use the Platform for, and will not allow the Platform to be used for, any purposes prohibited by United States law.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">15. DMCA Notification</h3>
                <p>If you are a copyright owner or an agent thereof and believe that any content made available via the Platform infringes upon your copyright, you may submit a notification pursuant to the Digital Millennium Copyright Act of 1998, 17 U.S.C. § 512 (the “DMCA”) by providing us with the following information in writing: (a) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; (b) identification of the claimed infringing material and information reasonably sufficient to permit us to locate the material on the Platform (providing the URL(s) of the claimed infringing material satisfies this requirement); (c) information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an email address; (d) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; (e) a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner’s behalf; and (f) your physical or electronic signature. Please send us all notices in connection with copyright infringements to: support@staging.confersolutions.ai.</p>
                <p><strong>15.1 Counter-Notice.</strong> If you feel that any of your material was improperly removed, please contact us via the contact information set forth above.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">16. Class Action Waiver</h3>
                <p>You and we hereby expressly waive their right to bring or participate in a class-action lawsuit. You and we agree that each may bring claims to the fullest extent legally permissible against the other only in their individual capacity and not as a plaintiff or class member in any purported class or representative proceeding. Further, unless both you and we agree otherwise, an arbitrator may not consolidate more than one person’s claims and may not otherwise preside over any form of a representative or class proceeding.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">17. Termination</h3>
                <p>This Agreement may be terminated by either you or us. This Agreement shall terminate automatically if and when we cease to operate our Platform servers. We may also terminate this Agreement if we find that you are using the Platform for illegal activities. You can terminate this Agreement by (i) requesting us to terminate and delete your Account in use to access or use the Platform or (ii) destroying and/or deleting any and all copies of all Platform in your possession, custody, or control. If we terminate this Agreement. If you request deletion of your Account, or if we delete your Account because you violated our terms and conditions. Your rights to use the Platform and your Account, will terminate immediately, and you must cease all use of the Platform upon the termination of this Agreement. The termination of this Agreement will not affect our rights or your obligations arising under this Agreement.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">18. Governing Law and Dispute Resolution</h3>
                <p>These Terms shall be governed and construed in accordance with the laws of the State of California without regard to its conflict of law provisions.</p>
                <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Platform and supersede and replace any prior agreements we might have had between us regarding Platform.</p>
                <p>Any dispute concerning the subject matter of these Terms, or the breach, termination, or validity thereof (a “Dispute”) will be settled exclusively in accordance with the procedures set forth herein.  The party seeking resolution of a Dispute will first give notice in writing of the Dispute to the other party, setting forth the nature of the Dispute and a concise statement of the issues to be resolved. If the Dispute has not been resolved through good faith efforts and negotiations of senior officers or representatives of the parties within fifteen (15) days of receipt by the relevant party of the notice of Dispute, such notice will be deemed to be a notice of arbitration and the parties agree to submit the Dispute to a single arbitrator mutually agreeable to both parties. The venue of such arbitration shall be California. In the event that the Parties cannot agree on a sole arbitrator, the arbitrator will be appointed by a judge of the appropriate court on application by either party to the Dispute. All decisions and awards rendered by the arbitrator will be final and binding upon the parties for all questions submitted to such arbitrator, and the costs associated with such submission shall be shared equally by the parties involved in the Dispute unless the arbitrator decides otherwise.  The parties waive all rights of appeal, therefore to any court or tribunal, and agree that the only recourse by any party to any court will be for the purpose of enforcing an arbitration award.</p>
              </section>

              <section className="mb-8">
                <h3 className="text-xl font-bold mb-2">19. General</h3>
                <ul>
                  <li><strong>19.1 No waiver.</strong> Our failure to enforce any part of this Agreement shall not constitute a waiver of our right to later enforce that or any other part of this Agreement. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future.</li>
                  <li><strong>19.2 Interpretation.</strong> The headers are provided only to make this Agreement easier to read and understand.</li>
                  <li><strong>19.3 Software Transfer.</strong> Your user rights are not transferable to third parties without a written permission by us.</li>
                  <li><strong>19.4 Severability.</strong> If any provisions mentioned in this Agreement are found to be unenforceable or invalid, that particular provision or provisions will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.</li>
                  <li><strong>19.5 Force Majeure.</strong> We will not be held liable for any delays or failure in performance of any part of the Platform, from any cause beyond our control. This includes, but is not limited to, acts of God, changes to law or regulations, embargoes, war, terrorist acts, riots, fires, earthquakes, nuclear accidents, floods, strikes, power blackouts, epidemics, pandemics, volcanic action, unusually severe weather conditions, and acts of hackers or third-party internet service providers.</li>
                  <li><strong>19.6 Notices.</strong> All notices under this Agreement shall be in writing Unless otherwise specified in this Agreement. Notices to us shall be sent by email to support@staging.confersolutions.ai. You shall ensure written confirmation of receipt for notice to be effective. Notices to you shall be sent to your last known email address (or the email address of your successor, if any) and/or to any email address that would be reasonably likely to provide notice to you, and such notice shall be effective upon transmission.</li>
                </ul>
              </section>
              {/* 12. Contact Information */}



            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
